// This file is auto-generated by @hey-api/openapi-ts

import type { RouteHandler } from 'fastify';

import type { IssuesGetData, IssuesGetErrors, IssuesGetResponses, IssuesGetSessionContentData, IssuesGetSessionContentErrors, IssuesGetSessionContentResponses, IssuesListData, IssuesListResponses, IssuesListSessionsData, IssuesListSessionsErrors, IssuesListSessionsResponses } from './types.gen.js';

export type RouteHandlers = {
    issuesList: RouteHandler<{
        Querystring?: IssuesListData['query'];
        Reply: IssuesListResponses;
    }>;
    issuesGet: RouteHandler<{
        Params: IssuesGetData['path'];
        Reply: IssuesGetErrors & IssuesGetResponses;
    }>;
    issuesListSessions: RouteHandler<{
        Params: IssuesListSessionsData['path'];
        Querystring?: IssuesListSessionsData['query'];
        Reply: IssuesListSessionsErrors & IssuesListSessionsResponses;
    }>;
    issuesGetSessionContent: RouteHandler<{
        Params: IssuesGetSessionContentData['path'];
        Reply: IssuesGetSessionContentErrors & IssuesGetSessionContentResponses;
    }>;
};
