// This file is auto-generated by @hey-api/openapi-ts

export const $Issue = {
    type: 'object',
    required: ['number', 'title', 'url', 'status'],
    properties: {
        number: {
            type: 'integer',
            format: 'int32',
            description: 'Issue number'
        },
        title: {
            type: 'string',
            description: 'Issue title'
        },
        url: {
            type: 'string',
            description: 'Issue URL'
        },
        status: {
            allOf: [
                {
                    '$ref': '#/components/schemas/IssueStatus'
                }
            ],
            description: 'Current status of the issue in Son of Anton workflow'
        },
        lastPlanCommentUrl: {
            type: 'string',
            description: 'URL to the comment containing the latest proposed plan'
        },
        prUrl: {
            type: 'string',
            description: 'URL to the Pull Request created for this issue'
        },
        branchName: {
            type: 'string',
            description: 'Name of the git branch on GitHub'
        },
        branchUrl: {
            type: 'string',
            description: 'URL to the git branch on GitHub'
        }
    }
} as const;

export const $IssueStatus = {
    type: 'string',
    enum: ['Planning', 'Waiting Plan review', 'Implementing', 'Waiting PR review', 'YOLO']
} as const;

export const $Session = {
    type: 'object',
    required: ['id', 'type', 'timestamp', 'status'],
    properties: {
        id: {
            type: 'string',
            description: 'Session ID (usually a timestamp)'
        },
        type: {
            type: 'string',
            enum: ['planning', 'implementing', 'addressing-review'],
            description: 'Type of the session'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            description: 'Timestamp when the session started'
        },
        status: {
            type: 'string',
            enum: ['success', 'failure'],
            description: 'Final status of the session'
        }
    }
} as const;