// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://tsp-output` | (string & {});
};

export type Issue = {
    /**
     * Issue number
     */
    number: number;
    /**
     * Issue title
     */
    title: string;
    /**
     * Issue URL
     */
    url: string;
    /**
     * Current status of the issue in Son of Anton workflow
     */
    status: IssueStatus;
    /**
     * URL to the comment containing the latest proposed plan
     */
    lastPlanCommentUrl?: string;
    /**
     * URL to the Pull Request created for this issue
     */
    prUrl?: string;
    /**
     * Name of the git branch on GitHub
     */
    branchName?: string;
    /**
     * URL to the git branch on GitHub
     */
    branchUrl?: string;
};

export enum IssueStatus {
    PLANNING = 'Planning',
    WAITING_PLAN_REVIEW = 'Waiting Plan review',
    IMPLEMENTING = 'Implementing',
    WAITING_PR_REVIEW = 'Waiting PR review',
    YOLO = 'YOLO'
}

export type Session = {
    /**
     * Session ID (usually a timestamp)
     */
    id: string;
    /**
     * Type of the session
     */
    type: 'planning' | 'implementing' | 'addressing-review';
    /**
     * Timestamp when the session started
     */
    timestamp: string;
    /**
     * Final status of the session
     */
    status: 'success' | 'failure';
};

export type IssuesListData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/issues';
};

export type IssuesListResponses = {
    /**
     * The request has succeeded.
     */
    200: {
        /**
         * Items in the current page
         */
        items: Array<Issue>;
        /**
         * Cursor for the next page of results
         */
        nextCursor?: string;
    };
};

export type IssuesListResponse = IssuesListResponses[keyof IssuesListResponses];

export type IssuesGetData = {
    body?: never;
    path: {
        number: number;
    };
    query?: never;
    url: '/issues/{number}';
};

export type IssuesGetErrors = {
    /**
     * The server cannot find the requested resource.
     */
    404: unknown;
};

export type IssuesGetResponses = {
    /**
     * The request has succeeded.
     */
    200: Issue;
};

export type IssuesGetResponse = IssuesGetResponses[keyof IssuesGetResponses];

export type IssuesListSessionsData = {
    body?: never;
    path: {
        number: number;
    };
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/issues/{number}/sessions';
};

export type IssuesListSessionsErrors = {
    /**
     * The server cannot find the requested resource.
     */
    404: unknown;
};

export type IssuesListSessionsResponses = {
    /**
     * The request has succeeded.
     */
    200: {
        /**
         * Items in the current page
         */
        items: Array<Session>;
        /**
         * Cursor for the next page of results
         */
        nextCursor?: string;
    };
};

export type IssuesListSessionsResponse = IssuesListSessionsResponses[keyof IssuesListSessionsResponses];

export type IssuesGetSessionContentData = {
    body?: never;
    path: {
        number: number;
        id: string;
    };
    query?: never;
    url: '/issues/{number}/sessions/{id}';
};

export type IssuesGetSessionContentErrors = {
    /**
     * The server cannot find the requested resource.
     */
    404: unknown;
};

export type IssuesGetSessionContentResponses = {
    /**
     * The request has succeeded.
     */
    200: string;
};

export type IssuesGetSessionContentResponse = IssuesGetSessionContentResponses[keyof IssuesGetSessionContentResponses];
