// This file is auto-generated by @hey-api/openapi-ts

export type Issue = {
    /**
     * Issue number
     */
    number: number;
    /**
     * Issue title
     */
    title: string;
    /**
     * Issue URL
     */
    url: string;
    /**
     * Current status of the issue in Son of Anton workflow
     */
    status: (IssueStatus);
    /**
     * URL to the comment containing the latest proposed plan
     */
    lastPlanCommentUrl?: string;
    /**
     * URL to the Pull Request created for this issue
     */
    prUrl?: string;
    /**
     * Name of the git branch on GitHub
     */
    branchName?: string;
    /**
     * URL to the git branch on GitHub
     */
    branchUrl?: string;
};

export type IssueStatus = 'Planning' | 'Waiting Plan review' | 'Implementing' | 'Waiting PR review' | 'YOLO';

export const IssueStatus = {
    PLANNING: 'Planning',
    WAITING_PLAN_REVIEW: 'Waiting Plan review',
    IMPLEMENTING: 'Implementing',
    WAITING_PR_REVIEW: 'Waiting PR review',
    YOLO: 'YOLO'
} as const;

export type Session = {
    /**
     * Session ID (usually a timestamp)
     */
    id: string;
    /**
     * Type of the session
     */
    type: 'planning' | 'implementing' | 'addressing-review';
    /**
     * Timestamp when the session started
     */
    timestamp: string;
    /**
     * Final status of the session
     */
    status: 'success' | 'failure';
};

/**
 * Type of the session
 */
export type type = 'planning' | 'implementing' | 'addressing-review';

/**
 * Type of the session
 */
export const type = {
    PLANNING: 'planning',
    IMPLEMENTING: 'implementing',
    ADDRESSING_REVIEW: 'addressing-review'
} as const;

/**
 * Final status of the session
 */
export type status = 'success' | 'failure';

/**
 * Final status of the session
 */
export const status = {
    SUCCESS: 'success',
    FAILURE: 'failure'
} as const;

export type IssuesListData = {
    cursor?: string;
    limit?: number;
};

export type IssuesListResponse = ({
    /**
     * Items in the current page
     */
    items: Array<Issue>;
    /**
     * Cursor for the next page of results
     */
    nextCursor?: string;
});

export type IssuesGetData = {
    number: number;
};

export type IssuesGetResponse = (Issue);

export type IssuesListSessionsData = {
    cursor?: string;
    limit?: number;
    number: number;
};

export type IssuesListSessionsResponse = ({
    /**
     * Items in the current page
     */
    items: Array<Session>;
    /**
     * Cursor for the next page of results
     */
    nextCursor?: string;
});

export type IssuesGetSessionContentData = {
    id: string;
    number: number;
};

export type IssuesGetSessionContentResponse = (string);

export type $OpenApiTs = {
    '/issues': {
        get: {
            req: IssuesListData;
            res: {
                /**
                 * The request has succeeded.
                 */
                200: {
                    /**
                     * Items in the current page
                     */
                    items: Array<Issue>;
                    /**
                     * Cursor for the next page of results
                     */
                    nextCursor?: string;
                };
            };
        };
    };
    '/issues/{number}': {
        get: {
            req: IssuesGetData;
            res: {
                /**
                 * The request has succeeded.
                 */
                200: Issue;
                /**
                 * The server cannot find the requested resource.
                 */
                404: unknown;
            };
        };
    };
    '/issues/{number}/sessions': {
        get: {
            req: IssuesListSessionsData;
            res: {
                /**
                 * The request has succeeded.
                 */
                200: {
                    /**
                     * Items in the current page
                     */
                    items: Array<Session>;
                    /**
                     * Cursor for the next page of results
                     */
                    nextCursor?: string;
                };
                /**
                 * The server cannot find the requested resource.
                 */
                404: unknown;
            };
        };
    };
    '/issues/{number}/sessions/{id}': {
        get: {
            req: IssuesGetSessionContentData;
            res: {
                /**
                 * The request has succeeded.
                 */
                200: string;
                /**
                 * The server cannot find the requested resource.
                 */
                404: unknown;
            };
        };
    };
};