/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all issues worked by Son of Anton */
        get: operations["Issues_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get details of a specific issue */
        get: operations["Issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{number}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all sessions associated with an issue */
        get: operations["Issues_listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{number}/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the full log content of a specific session */
        get: operations["Issues_getSessionContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Issue: {
            /**
             * Format: int32
             * @description Issue number
             */
            number: number;
            /** @description Issue title */
            title: string;
            /** @description Issue URL */
            url: string;
            /** @description Current status of the issue in Son of Anton workflow */
            status: components["schemas"]["IssueStatus"];
            /** @description URL to the comment containing the latest proposed plan */
            lastPlanCommentUrl?: string;
            /** @description URL to the Pull Request created for this issue */
            prUrl?: string;
            /** @description Name of the git branch on GitHub */
            branchName?: string;
            /** @description URL to the git branch on GitHub */
            branchUrl?: string;
        };
        /** @enum {string} */
        IssueStatus: "Planning" | "Waiting Plan review" | "Implementing" | "Waiting PR review" | "YOLO";
        Session: {
            /** @description Session ID (usually a timestamp) */
            id: string;
            /**
             * @description Type of the session
             * @enum {string}
             */
            type: "planning" | "implementing" | "addressing-review";
            /**
             * Format: date-time
             * @description Timestamp when the session started
             */
            timestamp: string;
            /**
             * @description Final status of the session
             * @enum {string}
             */
            status: "success" | "failure";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Issues_list: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Items in the current page */
                        items: components["schemas"]["Issue"][];
                        /** @description Cursor for the next page of results */
                        nextCursor?: string;
                    };
                };
            };
        };
    };
    Issues_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Issues_listSessions: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Items in the current page */
                        items: components["schemas"]["Session"][];
                        /** @description Cursor for the next page of results */
                        nextCursor?: string;
                    };
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Issues_getSessionContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
